//! Code emission for the build command.
//!
//! Takes discovered route entries (pages, layouts, error pages, components),
//! compiles each `.trs` file through the full pipeline, and writes all
//! generated Rust source files including:
//!
//! - A compiled module for each route / layout / error / component
//! - `mod.rs` files mirroring the directory tree
//! - An HTML document shell helper (`shell.rs`)
//! - A top-level `mod.rs` with an Axum router function
//!
//! Layouts wrap page output. Error pages are registered as 404 fallbacks.
//! Dynamic route segments use Axum `Path<…>` extraction.

use std::collections::BTreeMap;
use std::collections::HashMap;
use std::fmt::Write;
use std::fs;
use std::path::Path;
use std::path::PathBuf;

use anyhow::Context as _;
use anyhow::Result;

use crate::discover::RouteEntry;
use crate::discover::RouteKind;

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/// Compile all entries and write generated code to `output_dir`.
///
/// # Errors
///
/// Returns an error if any `.trs` file fails to parse or compile,
/// or if file I/O fails.
pub fn emit_all(entries: &[RouteEntry], output_dir: &Path) -> Result<()> {
  // Clean and recreate output directory.
  if output_dir.exists() {
    fs::remove_dir_all(output_dir)?;
  }
  fs::create_dir_all(output_dir)?;

  let routes_dir = output_dir.join("routes");
  fs::create_dir_all(&routes_dir)?;

  let comp_dir = output_dir.join("components");

  // Partition entries.
  let pages: Vec<_> = entries
    .iter()
    .filter(|e| e.kind == RouteKind::Page)
    .collect();
  let layouts: Vec<_> = entries
    .iter()
    .filter(|e| e.kind == RouteKind::Layout)
    .collect();
  let errors: Vec<_> = entries
    .iter()
    .filter(|e| e.kind == RouteKind::Error)
    .collect();
  let components: Vec<_> = entries
    .iter()
    .filter(|e| e.kind == RouteKind::Component)
    .collect();

  // Create components directory early if needed.
  if !components.is_empty() {
    fs::create_dir_all(&comp_dir)?;
  }

  // Build a set of known component names for import injection.
  // Components use lowercase module names with PascalCase aliases.
  let component_names: Vec<String> = components
    .iter()
    .map(|c| c.module_segments.last().expect("empty module segments").clone())
    .collect();

  // Compile and write each entry as a module.
  for entry in entries {
    match entry.kind {
      RouteKind::Component => {
        compile_trs(entry, &comp_dir, &[], true)?;
      }
      _ => compile_trs(entry, &routes_dir, &component_names, false)?,
    }
  }

  // Module tree for routes/.
  let route_entries: Vec<_> = entries
    .iter()
    .filter(|e| e.kind != RouteKind::Component)
    .cloned()
    .collect();
  let mod_tree = build_mod_tree(&route_entries);
  emit_mod_tree(&routes_dir, &mod_tree)?;

  // Module tree for components/ (lowercase module names).
  if !components.is_empty() {
    let mut comp_mod = String::from("// Auto-generated by thebe. Do not edit.\n");
    comp_mod.push_str("#![allow(clippy::all, unused)]\n\n");
    for name in &component_names {
      let lower = name.to_lowercase();
      writeln!(comp_mod, "pub mod {lower};").expect("write to String");
    }
    fs::write(comp_dir.join("mod.rs"), &comp_mod)?;
  }

  // shell.rs
  emit_shell(output_dir)?;

  // Build layout lookup: directory path → module path.
  let layout_map = build_layout_map(&layouts);

  // Find the root error page (if any).
  let root_error = errors.iter().find(|e| e.url_path == "/");

  // Top-level mod.rs with router.
  emit_root_mod(
    output_dir,
    &pages,
    &layout_map,
    root_error.copied(),
    &component_names,
  )?;

  Ok(())
}

// ---------------------------------------------------------------------------
// Single-file compilation
// ---------------------------------------------------------------------------

/// Compile a single `.trs` file and write the generated Rust module.
///
/// `component_names` is the list of known component module names (`PascalCase`).
/// For route modules (pages, layouts, errors), `use` imports are injected
/// so that `ComponentName::render()` calls in the generated code resolve
/// to the compiled component modules (which use lowercase file names).
///
/// When `lowercase_leaf` is true, the leaf module filename is lowercased
/// (used for component files to follow Rust naming conventions).
fn compile_trs(
  entry: &RouteEntry,
  base_dir: &Path,
  component_names: &[String],
  lowercase_leaf: bool,
) -> Result<()> {
  let source = fs::read_to_string(&entry.source_path)
    .with_context(|| format!("reading {}", entry.source_path.display()))?;
  let filename = entry.relative_path.to_str().unwrap_or("<unknown>");

  let ast = thebe_ast::parse(&source).map_err(|e| {
    let _ = thebe_ast::diagnostics::eprint_error(&e, &source, Some(filename));
    anyhow::anyhow!("parse error in {filename}")
  })?;

  let ir = thebe_compiler::lower(&source, &ast).map_err(|e| {
    let _ = thebe_compiler::diagnostics::eprint_error(&e, &source, Some(filename));
    anyhow::anyhow!("compile error in {filename}")
  })?;

  let warnings = thebe_compiler::validate(&ir);
  for w in &warnings {
    let _ = thebe_compiler::diagnostics::eprint_warning(w, &source, Some(filename));
  }

  let mut code = thebe_compiler::generate(&ir);

  // Inject `use` imports for any component this module references.
  // From a route module at depth N within `routes/`, the path to the
  // component is `super::` repeated (N+1) times, then `components::name`.
  if !component_names.is_empty() {
    let referenced: Vec<&String> = component_names
      .iter()
      .filter(|name| code.contains(&format!("{name}::render()")))
      .collect();

    if !referenced.is_empty() {
      // Module depth within `routes/`: segments give us how deep the module is
      // within the directory tree. We need one extra `super::` to escape the
      // `routes` module itself and reach the root where `components` lives.
      let supers = "super::".repeat(entry.module_segments.len() + 1);
      let mut imports = String::new();
      for name in &referenced {
        let lower = name.to_lowercase();
        writeln!(imports, "use {supers}components::{lower} as {name};")
          .expect("write to String");
      }
      imports.push('\n');
      code.insert_str(0, &imports);
    }
  }

  // Build target file path, creating intermediate directories.
  let mut target_dir = base_dir.to_path_buf();
  for segment in &entry.module_segments[..entry.module_segments.len() - 1] {
    target_dir = target_dir.join(segment);
    fs::create_dir_all(&target_dir)?;
  }

  let leaf = entry.module_segments.last().expect("empty module segments");
  let out_name = if lowercase_leaf {
    format!("{}.rs", leaf.to_lowercase())
  } else {
    format!("{leaf}.rs")
  };
  let file_path = target_dir.join(out_name);

  fs::write(&file_path, &code)
    .with_context(|| format!("writing {}", file_path.display()))?;

  Ok(())
}

// ---------------------------------------------------------------------------
// Module tree generation
// ---------------------------------------------------------------------------

/// A tree of module names used to generate `mod.rs` files.
#[derive(Default, Debug)]
struct ModTree {
  children: BTreeMap<String, ModTree>,
}

fn build_mod_tree(routes: &[RouteEntry]) -> ModTree {
  let mut root = ModTree::default();
  for route in routes {
    let mut node = &mut root;
    for segment in &route.module_segments {
      node = node.children.entry(segment.clone()).or_default();
    }
  }
  root
}

fn emit_mod_tree(dir: &Path, tree: &ModTree) -> Result<()> {
  if tree.children.is_empty() {
    return Ok(());
  }

  let mut content = String::from("// Auto-generated by thebe. Do not edit.\n");
  content.push_str("#![allow(clippy::all, unused)]\n\n");

  for name in tree.children.keys() {
    writeln!(content, "pub mod {name};").expect("write to String");
  }

  fs::write(dir.join("mod.rs"), &content)?;

  for (name, child) in &tree.children {
    if !child.children.is_empty() {
      let child_dir = dir.join(name);
      fs::create_dir_all(&child_dir)?;
      emit_mod_tree(&child_dir, child)?;
    }
  }

  Ok(())
}

// ---------------------------------------------------------------------------
// Layout map
// ---------------------------------------------------------------------------

/// Build a mapping from directory relative path → layout module path.
///
/// `_layout.trs` (root) → `["_layout"]`
/// `blog/_layout.trs` → `["blog", "_layout"]`
fn build_layout_map(layouts: &[&RouteEntry]) -> HashMap<PathBuf, Vec<String>> {
  let mut map = HashMap::new();
  for layout in layouts {
    let dir = layout
      .relative_path
      .parent()
      .unwrap_or(Path::new(""))
      .to_path_buf();
    map.insert(dir, layout.module_segments.clone());
  }
  map
}

/// Find the most specific layout for a page route.
///
/// Walks from the page's directory up to the root, returning the first
/// matching layout module path.
fn find_layout_for_page(
  page: &RouteEntry,
  layout_map: &HashMap<PathBuf, Vec<String>>,
) -> Option<Vec<String>> {
  let mut dir = page
    .relative_path
    .parent()
    .unwrap_or(Path::new(""))
    .to_path_buf();

  loop {
    if let Some(layout_mod) = layout_map.get(&dir) {
      return Some(layout_mod.clone());
    }
    if !dir.pop() {
      // Check root.
      return layout_map.get(&PathBuf::new()).cloned();
    }
  }
}

// ---------------------------------------------------------------------------
// Shell (HTML document wrapper)
// ---------------------------------------------------------------------------

fn emit_shell(output_dir: &Path) -> Result<()> {
  let content = r#"// Auto-generated by thebe. Do not edit.

/// Wrap a rendered component body in a full HTML document.
pub fn document(body: &str, styles: &[&str]) -> String {
  let mut html = String::from("<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n");
  html.push_str("<meta charset=\"utf-8\">\n");
  html.push_str("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
  for css in styles {
    if !css.is_empty() {
      html.push_str("<style>");
      html.push_str(css);
      html.push_str("</style>\n");
    }
  }
  html.push_str("</head>\n<body>\n");
  html.push_str(body);
  html.push_str("\n</body>\n</html>");
  html
}
"#;

  fs::write(output_dir.join("shell.rs"), content)?;
  Ok(())
}

// ---------------------------------------------------------------------------
// Root module + router
// ---------------------------------------------------------------------------

/// Write the top-level `mod.rs` with the Axum router function.
#[allow(clippy::too_many_lines)]
fn emit_root_mod(
  output_dir: &Path,
  pages: &[&RouteEntry],
  layout_map: &HashMap<PathBuf, Vec<String>>,
  root_error: Option<&RouteEntry>,
  component_names: &[String],
) -> Result<()> {
  let has_components = !component_names.is_empty();
  let mut code = String::from("// Auto-generated by thebe. Do not edit.\n");
  code.push_str("#![allow(clippy::all, unused)]\n\n");
  code.push_str("pub mod routes;\nmod shell;\n");

  if has_components {
    code.push_str("pub mod components;\n");
  }

  code.push('\n');

  // Router function.
  code.push_str("/// Build an [`axum::Router`] with all discovered routes.\n");
  code.push_str("pub fn router() -> axum::Router {\n");
  code.push_str("  axum::Router::new()\n");

  for page in pages {
    let handler = handler_name(&page.module_segments);
    writeln!(
      code,
      "    .route(\"{}\", axum::routing::get({handler}))",
      page.url_path
    )
    .expect("write to String");
  }

  // 404 fallback if there's a root _error.trs.
  if root_error.is_some() {
    code.push_str("    .fallback(__fallback)\n");
  }

  code.push_str("}\n");

  // Handler functions for each page.
  for page in pages {
    let handler = handler_name(&page.module_segments);
    let mod_path = page.module_segments.join("::");
    let layout_mod = find_layout_for_page(page, layout_map);

    code.push('\n');

    if page.params.is_empty() {
      // Static route — no path params.
      writeln!(
        code,
        "async fn {handler}() -> axum::response::Html<String> {{"
      )
      .expect("write to String");
    } else {
      // Dynamic route — extract path params.
      if page.params.len() == 1 {
        // Single param: Path<String>
        writeln!(
          code,
          "async fn {handler}(\n  axum::extract::Path({}): axum::extract::Path<String>,\n) -> axum::response::Html<String> {{",
          page.params[0]
        )
        .expect("write to String");
      } else {
        // Multiple params: Path<(String, String, ...)>
        let param_types = build_param_types(&page.params);
        writeln!(
          code,
          "async fn {handler}(\n  axum::extract::Path(({})): axum::extract::Path<({param_types})>,\n) -> axum::response::Html<String> {{",
          page.params.join(", ")
        )
        .expect("write to String");
      }
    }

    // Render the page body.
    writeln!(code, "  let body = routes::{mod_path}::render();")
      .expect("write to String");

    // Wrap in layout if one exists.
    if let Some(layout_segs) = &layout_mod {
      let layout_path = layout_segs.join("::");
      writeln!(
        code,
        "  let body = routes::{layout_path}::render_with_slot(&body);"
      )
      .expect("write to String");
    }

    // Collect styles.
    writeln!(code, "  let mut all_styles: Vec<&str> = Vec::new();")
      .expect("write to String");
    writeln!(
      code,
      "  all_styles.extend_from_slice(routes::{mod_path}::STYLES);"
    )
    .expect("write to String");
    if let Some(layout_segs) = &layout_mod {
      let layout_path = layout_segs.join("::");
      writeln!(
        code,
        "  all_styles.extend_from_slice(routes::{layout_path}::STYLES);"
      )
      .expect("write to String");
    }
    for comp_name in component_names {
      let lower = comp_name.to_lowercase();
      writeln!(
        code,
        "  all_styles.extend_from_slice(components::{lower}::STYLES);"
      )
      .expect("write to String");
    }

    writeln!(
      code,
      "  axum::response::Html(shell::document(&body, &all_styles))"
    )
    .expect("write to String");
    code.push_str("}\n");
  }

  // 404 fallback handler.
  if let Some(err) = root_error {
    let err_mod = err.module_segments.join("::");
    code.push('\n');
    code.push_str("async fn __fallback() -> (axum::http::StatusCode, axum::response::Html<String>) {\n");
    writeln!(code, "  let body = routes::{err_mod}::render();")
      .expect("write to String");
    writeln!(
      code,
      "  let styles = routes::{err_mod}::STYLES;"
    )
    .expect("write to String");
    code.push_str(
      "  (axum::http::StatusCode::NOT_FOUND, axum::response::Html(shell::document(&body, styles)))\n",
    );
    code.push_str("}\n");
  }

  fs::write(output_dir.join("mod.rs"), &code)?;
  Ok(())
}

/// Build Axum `Path` type tuple: all `String`.
fn build_param_types(params: &[String]) -> String {
  std::iter::repeat_n("String", params.len())
    .collect::<Vec<_>>()
    .join(", ")
}

/// Build a unique handler function name from module segments.
///
/// Strips leading underscores from dynamic segments to avoid double
/// underscores in the name (e.g. `["blog", "_slug"]` → `__route_blog_slug`).
fn handler_name(segments: &[String]) -> String {
  let clean: Vec<_> = segments
    .iter()
    .map(|s| s.trim_start_matches('_'))
    .collect();
  format!("__route_{}", clean.join("_"))
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
  use super::*;
  use std::collections::BTreeSet;

  #[test]
  fn handler_name_flat() {
    let segs = vec!["index".to_string()];
    assert_eq!(handler_name(&segs), "__route_index");
  }

  #[test]
  fn handler_name_nested() {
    let segs = vec!["blog".to_string(), "post".to_string()];
    assert_eq!(handler_name(&segs), "__route_blog_post");
  }

  #[test]
  fn handler_name_dynamic() {
    let segs = vec!["blog".to_string(), "_id".to_string()];
    assert_eq!(handler_name(&segs), "__route_blog_id");
  }

  #[test]
  fn mod_tree_flat() {
    let routes = vec![entry(&["index"], RouteKind::Page), entry(&["about"], RouteKind::Page)];
    let tree = build_mod_tree(&routes);
    let names: Vec<_> = tree.children.keys().collect();
    assert_eq!(names, vec!["about", "index"]);
  }

  #[test]
  fn mod_tree_nested() {
    let routes = vec![
      entry(&["index"], RouteKind::Page),
      entry(&["blog", "index"], RouteKind::Page),
      entry(&["blog", "post"], RouteKind::Page),
    ];
    let tree = build_mod_tree(&routes);
    assert!(tree.children.contains_key("blog"));
    let blog = &tree.children["blog"];
    let blog_children: BTreeSet<_> = blog.children.keys().cloned().collect();
    assert!(blog_children.contains("index"));
    assert!(blog_children.contains("post"));
  }

  #[test]
  fn param_types_single() {
    assert_eq!(build_param_types(&["id".into()]), "String");
  }

  #[test]
  fn param_types_multiple() {
    assert_eq!(
      build_param_types(&["org".into(), "repo".into()]),
      "String, String"
    );
  }

  #[test]
  fn layout_map_root() {
    let layout = route_entry(&["_layout"], RouteKind::Layout, "_layout.trs");
    let map = build_layout_map(&[&layout]);
    assert!(map.contains_key(&PathBuf::new()));
  }

  #[test]
  fn layout_map_nested() {
    let layout = route_entry(&["blog", "_layout"], RouteKind::Layout, "blog/_layout.trs");
    let map = build_layout_map(&[&layout]);
    assert!(map.contains_key(&PathBuf::from("blog")));
  }

  #[test]
  fn find_layout_root() {
    let layout = route_entry(&["_layout"], RouteKind::Layout, "_layout.trs");
    let map = build_layout_map(&[&layout]);
    let page = route_entry(&["index"], RouteKind::Page, "index.trs");
    let found = find_layout_for_page(&page, &map);
    assert_eq!(found, Some(vec!["_layout".to_string()]));
  }

  #[test]
  fn find_layout_nested_inherits_parent() {
    let layout = route_entry(&["_layout"], RouteKind::Layout, "_layout.trs");
    let map = build_layout_map(&[&layout]);
    let page = route_entry(&["blog", "post"], RouteKind::Page, "blog/post.trs");
    let found = find_layout_for_page(&page, &map);
    assert_eq!(found, Some(vec!["_layout".to_string()]));
  }

  #[test]
  fn find_layout_nearest_wins() {
    let root_layout = route_entry(&["_layout"], RouteKind::Layout, "_layout.trs");
    let blog_layout =
      route_entry(&["blog", "_layout"], RouteKind::Layout, "blog/_layout.trs");
    let map = build_layout_map(&[&root_layout, &blog_layout]);
    let page = route_entry(&["blog", "post"], RouteKind::Page, "blog/post.trs");
    let found = find_layout_for_page(&page, &map);
    assert_eq!(
      found,
      Some(vec!["blog".to_string(), "_layout".to_string()])
    );
  }

  #[test]
  fn find_layout_none() {
    let map = HashMap::new();
    let page = route_entry(&["about"], RouteKind::Page, "about.trs");
    assert_eq!(find_layout_for_page(&page, &map), None);
  }

  /// Helper with minimal fields.
  fn entry(segments: &[&str], kind: RouteKind) -> RouteEntry {
    RouteEntry {
      source_path: PathBuf::new(),
      relative_path: PathBuf::new(),
      url_path: String::new(),
      module_segments: segments.iter().map(|s| (*s).to_string()).collect(),
      kind,
      params: Vec::new(),
    }
  }

  /// Helper with a relative path for layout lookups.
  fn route_entry(segments: &[&str], kind: RouteKind, rel: &str) -> RouteEntry {
    RouteEntry {
      source_path: PathBuf::new(),
      relative_path: PathBuf::from(rel),
      url_path: String::new(),
      module_segments: segments.iter().map(|s| (*s).to_string()).collect(),
      kind,
      params: Vec::new(),
    }
  }
}
