pub mod diagnostics;
mod parser;
mod template;
mod types;

pub use parser::parse;
pub use template::parse_html;
pub use template::parse_template;
pub use types::Attribute;
pub use types::Directive;
pub use types::DirectiveKind;
pub use types::Element;
pub use types::HtmlNode;
pub use types::IfBranch;
pub use types::ParseError;
pub use types::ScriptBlock;
pub use types::Span;
pub use types::StyleBlock;
pub use types::TemplateFragment;
pub use types::TemplateNode;
pub use types::ThebeAst;
