//! SSR code generation for compiled `.trs` components.
//!
//! Takes a [`CompiledComponent`] (the IR) and generates a self-contained
//! Rust module string with a `render()` function that returns HTML.

use crate::ir::CompiledComponent;
use crate::ir::IrAttribute;
use crate::ir::IrComponentRef;
use crate::ir::IrEach;
use crate::ir::IrElement;
use crate::ir::IrIf;
use crate::ir::IrNode;
use crate::ir::IrSlot;

use thebe_ast::TemplateNode;

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/// Generate Rust source code from a compiled component.
///
/// The returned string is a self-contained Rust module with:
/// - A `render()` function that returns an HTML string (SSR)
/// - `STYLES` / `SCOPE_IDS` constants for style metadata
/// - An internal `__esc` HTML-escape helper
///
/// # Example output
///
/// ```text
/// // Auto-generated by thebe-compiler. Do not edit.
///
/// pub fn render() -> String {
///   let mut __html = String::new();
///   __html.push_str("<div>hello</div>");
///   __html
/// }
/// ```
#[must_use]
pub fn generate(component: &CompiledComponent) -> String {
  let scope_attrs = build_scope_attrs(component);
  let mut e = Emitter::new(scope_attrs);
  e.emit_module(component);
  e.finish()
}

/// Build the concatenated scope attribute string for scoped styles.
///
/// For a component with scope id `s-abcdef01`, this returns `" data-s-abcdef01"`.
fn build_scope_attrs(component: &CompiledComponent) -> String {
  use std::fmt::Write;
  let mut out = String::new();
  for style in &component.styles {
    if let Some(id) = &style.scope_id {
      write!(out, " data-{id}").unwrap();
    }
  }
  out
}

// ---------------------------------------------------------------------------
// Emitter
// ---------------------------------------------------------------------------

struct Emitter {
  buf: String,
  indent: usize,
  /// Pre-built HTML attribute string for scoped style isolation,
  /// e.g. `" data-s-abcdef01"`. Empty when there are no scoped styles.
  scope_attrs: String,
  /// Whether we're emitting the slotted variant of render.
  slotted: bool,
}

impl Emitter {
  fn new(scope_attrs: String) -> Self {
    Self {
      buf: String::new(),
      indent: 0,
      scope_attrs,
      slotted: false,
    }
  }

  fn finish(self) -> String {
    self.buf
  }

  /// Emit one indented line (or a blank line if `text` is empty).
  fn line(&mut self, text: &str) {
    if text.is_empty() {
      self.buf.push('\n');
      return;
    }
    for _ in 0..self.indent {
      self.buf.push_str("  ");
    }
    self.buf.push_str(text);
    self.buf.push('\n');
  }

  fn indent(&mut self) {
    self.indent += 1;
  }

  fn dedent(&mut self) {
    self.indent -= 1;
  }

  // ── Module structure ────────────────────────────────────────────────

  fn emit_module(&mut self, c: &CompiledComponent) {
    self.line("// Auto-generated by thebe-compiler. Do not edit.");
    self.line("");
    self.emit_render(c);
    self.line("");
    self.emit_style_constants(c);
    self.line("");
    self.emit_esc();
  }

  fn emit_render(&mut self, c: &CompiledComponent) {
    self.line("/// Render this component to an HTML string.");
    self.line("#[allow(clippy::all, unused)]");
    self.line("pub fn render() -> String {");
    self.indent();
    self.emit_render_body(c, false);
    self.dedent();
    self.line("}");

    // Also emit render_with_slot for layout support.
    self.line("");
    self.line("/// Render this component, injecting `__slot` content in place of `<slot />`.");
    self.line("#[allow(clippy::all, unused)]");
    self.line("pub fn render_with_slot(__slot: &str) -> String {");
    self.indent();
    self.emit_render_body(c, true);
    self.dedent();
    self.line("}");
  }

  fn emit_render_body(&mut self, c: &CompiledComponent, slotted: bool) {
    if let Some(setup) = &c.setup {
      for l in setup.content.lines() {
        self.line(l);
      }
      self.line("");
    }

    self.line("let mut __html = String::new();");

    self.slotted = slotted;
    for node in &c.template {
      self.emit_node(node);
    }
    self.slotted = false;

    self.line("__html");
  }

  // ── Node emission ───────────────────────────────────────────────────

  fn emit_node(&mut self, node: &IrNode) {
    match node {
      IrNode::Text(text) => {
        if !text.is_empty() {
          self.line(&format!("__html.push_str(\"{}\");", esc_rs(text)));
        }
      }
      IrNode::Expr(e) => {
        self.line(&format!(
          "__html.push_str(&__esc(&format!(\"{{}}\", {{ {} }})));",
          e.expr
        ));
      }
      IrNode::Element(el) => self.emit_element(el),
      IrNode::If(ib) => self.emit_if(ib),
      IrNode::Each(each) => self.emit_each(each),
      IrNode::Component(comp) => self.emit_component(comp),
      IrNode::Slot(slot) => self.emit_slot(slot),
    }
  }

  fn emit_element(&mut self, el: &IrElement) {
    // Open tag name.
    self.line(&format!("__html.push_str(\"<{}\");", el.tag));

    // Attributes.
    for attr in &el.attributes {
      self.emit_attr(attr);
    }

    // Scope attributes for scoped style isolation.
    let scope = self.scope_attrs.clone();
    if !scope.is_empty() {
      self.line(&format!("__html.push_str(\"{}\");", esc_rs(&scope)));
    }

    if el.self_closing {
      self.line("__html.push_str(\" />\");");
    } else {
      self.line("__html.push_str(\">\");");
      for child in &el.children {
        self.emit_node(child);
      }
      self.line(&format!("__html.push_str(\"</{}>\");", el.tag));
    }
  }

  fn emit_attr(&mut self, attr: &IrAttribute) {
    if attr.value.is_empty() {
      // Boolean attribute.
      self.line(&format!("__html.push_str(\" {}\");", attr.name));
      return;
    }

    let all_static = attr
      .value
      .iter()
      .all(|v| matches!(v, TemplateNode::Text(_)));

    if all_static {
      // Inline the whole attribute as one push_str.
      let val: String = attr
        .value
        .iter()
        .map(|v| match v {
          TemplateNode::Text(t) => t.as_str(),
          TemplateNode::Expr { .. } => unreachable!(),
        })
        .collect();
      self.line(&format!(
        "__html.push_str(\" {}=\\\"{}\\\"\");",
        attr.name,
        esc_rs(&val)
      ));
    } else {
      // Dynamic attribute — build value piece-by-piece.
      self.line(&format!("__html.push_str(\" {}=\\\"\");", attr.name));
      for part in &attr.value {
        match part {
          TemplateNode::Text(t) => {
            self.line(&format!("__html.push_str(\"{}\");", esc_rs(t)));
          }
          TemplateNode::Expr { expr, .. } => {
            self.line(
              &format!("__html.push_str(&__esc(&format!(\"{{}}\", {{ {expr} }})));"),
            );
          }
        }
      }
      self.line("__html.push_str(\"\\\"\");");
    }
  }

  fn emit_if(&mut self, ib: &IrIf) {
    for (i, branch) in ib.branches.iter().enumerate() {
      if i == 0 {
        let cond = branch.condition.as_deref().unwrap_or("true");
        self.line(&format!("if {cond} {{"));
      } else if let Some(cond) = &branch.condition {
        self.line(&format!("}} else if {cond} {{"));
      } else {
        self.line("} else {");
      }
      self.indent();
      for child in &branch.children {
        self.emit_node(child);
      }
      self.dedent();
    }
    self.line("}");
  }

  fn emit_each(&mut self, each: &IrEach) {
    if let Some(idx) = &each.index {
      self.line(&format!(
        "for ({idx}, {}) in ({}).into_iter().enumerate() {{",
        each.binding, each.iterable
      ));
    } else {
      self.line(&format!(
        "for {} in {} {{",
        each.binding, each.iterable
      ));
    }
    self.indent();
    for child in &each.children {
      self.emit_node(child);
    }
    self.dedent();
    self.line("}");
  }

  fn emit_component(&mut self, comp: &IrComponentRef) {
    // SSR: call the component's render function and append its output.
    // TODO: pass props and slot content once component resolution is in place.
    self.line(&format!(
      "__html.push_str(&{}::render());",
      comp.name
    ));
  }

  fn emit_slot(&mut self, slot: &IrSlot) {
    if self.slotted {
      // In slotted mode, inject the passed slot content.
      self.line("__html.push_str(__slot);");
    } else {
      // In standalone mode, render fallback content.
      for child in &slot.fallback {
        self.emit_node(child);
      }
    }
  }

  // ── Style / escape helpers ──────────────────────────────────────────

  fn emit_style_constants(&mut self, c: &CompiledComponent) {
    self.line("/// CSS content of this component's style blocks.");
    if c.styles.is_empty() {
      self.line("pub const STYLES: &[&str] = &[];");
    } else {
      self.line("pub const STYLES: &[&str] = &[");
      self.indent();
      for style in &c.styles {
        self.line(&format!("\"{}\",", esc_rs(&style.content)));
      }
      self.dedent();
      self.line("];");
    }

    self.line("");

    let scope_ids: Vec<_> = c
      .styles
      .iter()
      .filter_map(|s| s.scope_id.as_ref())
      .collect();
    self.line("/// Scope identifiers for scoped style blocks.");
    if scope_ids.is_empty() {
      self.line("pub const SCOPE_IDS: &[&str] = &[];");
    } else {
      self.line("pub const SCOPE_IDS: &[&str] = &[");
      self.indent();
      for id in &scope_ids {
        self.line(&format!("\"{id}\","));
      }
      self.dedent();
      self.line("];");
    }
  }

  fn emit_esc(&mut self) {
    self.line("#[allow(dead_code)]");
    self.line("fn __esc(s: &str) -> String {");
    self.indent();
    self.line("let mut out = String::with_capacity(s.len());");
    self.line("for c in s.chars() {");
    self.indent();
    self.line("match c {");
    self.indent();
    self.line("'&' => out.push_str(\"&amp;\"),");
    self.line("'<' => out.push_str(\"&lt;\"),");
    self.line("'>' => out.push_str(\"&gt;\"),");
    self.line("'\"' => out.push_str(\"&quot;\"),");
    self.line("'\\'' => out.push_str(\"&#x27;\"),");
    self.line("_ => out.push(c),");
    self.dedent();
    self.line("}");
    self.dedent();
    self.line("}");
    self.line("out");
    self.dedent();
    self.line("}");
  }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/// Escape a string for inclusion inside a Rust string literal.
fn esc_rs(s: &str) -> String {
  s.replace('\\', "\\\\")
    .replace('"', "\\\"")
    .replace('\n', "\\n")
    .replace('\r', "\\r")
    .replace('\t', "\\t")
}
