//! SSR code generation for compiled `.trs` components.
//!
//! Takes a [`CompiledComponent`] (the IR) and generates a self-contained
//! Rust module string with a `render()` function that returns HTML.

use crate::ir::CompiledComponent;
use crate::ir::IrAction;
use crate::ir::IrAttribute;
use crate::ir::IrBinding;
use crate::ir::IrClassToggle;
use crate::ir::IrComponentRef;
use crate::ir::IrEach;
use crate::ir::IrElement;
use crate::ir::IrEventHandler;
use crate::ir::IrIf;
use crate::ir::IrNode;
use crate::ir::IrSlot;
use crate::ir::IrStyleProp;
use crate::ir::EventModifier;

use thebe_ast::TemplateNode;

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/// Generate Rust source code from a compiled component.
///
/// The returned string is a self-contained Rust module with:
/// - A `render()` function that returns an HTML string (SSR)
/// - `STYLES` / `SCOPE_IDS` constants for style metadata
/// - An internal `__esc` HTML-escape helper
///
/// `route_params` lists the dynamic route segment names for this page
/// (e.g. `["slug"]` for a `[slug].trs` route).  When non-empty the
/// generated `render()` function accepts those as `&str` parameters,
/// making them available to `<script setup>` code and expressions.
///
/// # Example output
///
/// ```text
/// // Auto-generated by thebe-compiler. Do not edit.
///
/// pub fn render() -> String {
///   let mut __html = String::new();
///   __html.push_str("<div>hello</div>");
///   __html
/// }
/// ```
#[must_use]
pub fn generate(component: &CompiledComponent, route_params: &[String]) -> String {
  let scope_attrs = build_scope_attrs(component);
  let mut e = Emitter::new(scope_attrs);
  e.emit_module(component, route_params);
  e.finish()
}

/// Build the concatenated scope attribute string for scoped styles.
///
/// For a component with scope id `s-abcdef01`, this returns `" data-s-abcdef01"`.
fn build_scope_attrs(component: &CompiledComponent) -> String {
  use std::fmt::Write;
  let mut out = String::new();
  for style in &component.styles {
    if let Some(id) = &style.scope_id {
      write!(out, " data-{id}").unwrap();
    }
  }
  out
}

// ---------------------------------------------------------------------------
// Emitter
// ---------------------------------------------------------------------------

struct Emitter {
  buf: String,
  indent: usize,
  /// Pre-built HTML attribute string for scoped style isolation,
  /// e.g. `" data-s-abcdef01"`. Empty when there are no scoped styles.
  scope_attrs: String,
  /// Whether we're emitting the slotted variant of render.
  slotted: bool,
}

impl Emitter {
  fn new(scope_attrs: String) -> Self {
    Self {
      buf: String::new(),
      indent: 0,
      scope_attrs,
      slotted: false,
    }
  }

  fn finish(self) -> String {
    self.buf
  }

  /// Emit one indented line (or a blank line if `text` is empty).
  fn line(&mut self, text: &str) {
    if text.is_empty() {
      self.buf.push('\n');
      return;
    }
    for _ in 0..self.indent {
      self.buf.push_str("  ");
    }
    self.buf.push_str(text);
    self.buf.push('\n');
  }

  fn indent(&mut self) {
    self.indent += 1;
  }

  fn dedent(&mut self) {
    self.indent -= 1;
  }

  // ── Module structure ────────────────────────────────────────────────

  fn emit_module(&mut self, c: &CompiledComponent, route_params: &[String]) {
    self.line("// Auto-generated by thebe-compiler. Do not edit.");
    self.line("");
    self.emit_render(c, route_params);
    self.line("");
    self.emit_style_constants(c);
    self.line("");
    self.emit_esc();
  }

  fn emit_render(&mut self, c: &CompiledComponent, route_params: &[String]) {
    self.line("/// Render this component to an HTML string.");
    self.line("#[allow(clippy::all, unused)]");

    if route_params.is_empty() {
      self.line("pub fn render() -> String {");
    } else {
      let params: String = route_params
        .iter()
        .map(|p| format!("{p}: &str"))
        .collect::<Vec<_>>()
        .join(", ");
      self.line(&format!("pub fn render({params}) -> String {{"));
    }
    self.indent();
    self.emit_render_body(c, false);
    self.dedent();
    self.line("}");

    // Also emit render_with_slot for layout support.
    self.line("");
    self.line("/// Render this component, injecting `__slot` content in place of `<slot />`.");
    self.line("#[allow(clippy::all, unused)]");

    if route_params.is_empty() {
      self.line("pub fn render_with_slot(__slot: &str) -> String {");
    } else {
      let params: String = route_params
        .iter()
        .map(|p| format!("{p}: &str"))
        .collect::<Vec<_>>()
        .join(", ");
      self.line(&format!(
        "pub fn render_with_slot(__slot: &str, {params}) -> String {{"
      ));
    }
    self.indent();
    self.emit_render_body(c, true);
    self.dedent();
    self.line("}");
  }

  fn emit_render_body(&mut self, c: &CompiledComponent, slotted: bool) {
    if let Some(setup) = &c.setup {
      for l in setup.content.lines() {
        self.line(l);
      }
      self.line("");
    }

    self.line("let mut __html = String::new();");

    // Declare named slot variables so that `<slot name="X">` fallback
    // logic compiles. These are initialised to `None` here; once full
    // named-slot passing is wired up the caller will supply real values.
    let named_slots = collect_named_slots(&c.template);
    for name in &named_slots {
      self.line(&format!(
        "let __slot_{name}: Option<&str> = None;"
      ));
    }

    self.slotted = slotted;
    for node in &c.template {
      self.emit_node(node);
    }
    self.slotted = false;

    self.line("__html");
  }

  // ── Node emission ───────────────────────────────────────────────────

  fn emit_node(&mut self, node: &IrNode) {
    match node {
      IrNode::Text(text) => {
        if !text.is_empty() {
          self.line(&format!("__html.push_str(\"{}\");", esc_rs(text)));
        }
      }
      IrNode::Expr(e) => {
        self.line(&format!(
          "__html.push_str(&__esc(&format!(\"{{}}\", {{ {} }})));",
          e.expr
        ));
      }
      IrNode::Element(el) => self.emit_element(el),
      IrNode::If(ib) => self.emit_if(ib),
      IrNode::Each(each) => self.emit_each(each),
      IrNode::Component(comp) => self.emit_component(comp),
      IrNode::Slot(slot) => self.emit_slot(slot),
    }
  }

  fn emit_element(&mut self, el: &IrElement) {
    // Open tag name.
    self.line(&format!("__html.push_str(\"<{}\");", el.tag));

    // Static and dynamic attributes.
    for attr in &el.attributes {
      self.emit_attr(attr);
    }

    // Conditional CSS classes (class:name="condition").
    if !el.class_toggles.is_empty() {
      self.emit_class_toggles(&el.class_toggles);
    }

    // Inline style properties (style:prop="value").
    if !el.style_props.is_empty() {
      self.emit_style_props(&el.style_props);
    }

    // Event handlers (on:event="handler") — emitted as data attributes
    // for client-side hydration.
    for event in &el.events {
      self.emit_event_handler(event);
    }

    // Two-way bindings (bind:prop="expr") — emitted as data attributes
    // for client-side hydration.
    for binding in &el.bindings {
      self.emit_binding(binding);
    }

    // Action hooks (use:action="arg") — emitted as data attributes
    // for client-side hydration.
    for action in &el.actions {
      self.emit_action(action);
    }

    // Scope attributes for scoped style isolation.
    let scope = self.scope_attrs.clone();
    if !scope.is_empty() {
      self.line(&format!("__html.push_str(\"{}\");", esc_rs(&scope)));
    }

    if el.self_closing {
      self.line("__html.push_str(\" />\");");
    } else {
      self.line("__html.push_str(\">\");");
      for child in &el.children {
        self.emit_node(child);
      }
      self.line(&format!("__html.push_str(\"</{}>\");", el.tag));
    }
  }

  fn emit_attr(&mut self, attr: &IrAttribute) {
    if attr.value.is_empty() {
      // Boolean attribute.
      self.line(&format!("__html.push_str(\" {}\");", attr.name));
      return;
    }

    let all_static = attr
      .value
      .iter()
      .all(|v| matches!(v, TemplateNode::Text(_)));

    if all_static {
      // Inline the whole attribute as one push_str.
      let val: String = attr
        .value
        .iter()
        .map(|v| match v {
          TemplateNode::Text(t) => t.as_str(),
          TemplateNode::Expr { .. } => unreachable!(),
        })
        .collect();
      self.line(&format!(
        "__html.push_str(\" {}=\\\"{}\\\"\");",
        attr.name,
        esc_rs(&val)
      ));
    } else {
      // Dynamic attribute — build value piece-by-piece.
      self.line(&format!("__html.push_str(\" {}=\\\"\");", attr.name));
      for part in &attr.value {
        match part {
          TemplateNode::Text(t) => {
            self.line(&format!("__html.push_str(\"{}\");", esc_rs(t)));
          }
          TemplateNode::Expr { expr, .. } => {
            self.line(
              &format!("__html.push_str(&__esc(&format!(\"{{}}\", {{ {expr} }})));"),
            );
          }
        }
      }
      self.line("__html.push_str(\"\\\"\");");
    }
  }

  /// Emit conditional CSS class toggles as a single `class` attribute fragment.
  ///
  /// For `class:active="is_active"` and `class:hidden="!visible"`, generates:
  /// ```text
  /// {
  ///   let mut __classes = Vec::new();
  ///   if is_active { __classes.push("active"); }
  ///   if !visible { __classes.push("hidden"); }
  ///   if !__classes.is_empty() {
  ///     __html.push_str(" class=\"");
  ///     __html.push_str(&__classes.join(" "));
  ///     __html.push_str("\"");
  ///   }
  /// }
  /// ```
  fn emit_class_toggles(&mut self, toggles: &[IrClassToggle]) {
    // Filter out toggles with empty conditions — they would produce invalid Rust.
    let valid: Vec<_> = toggles
      .iter()
      .filter(|t| !t.condition.trim().is_empty())
      .collect();
    if valid.is_empty() {
      return;
    }
    self.line("{");
    self.indent();
    self.line("let mut __classes = Vec::new();");
    for toggle in &valid {
      self.line(&format!(
        "if {} {{ __classes.push(\"{}\"); }}",
        toggle.condition, toggle.class
      ));
    }
    self.line("if !__classes.is_empty() {");
    self.indent();
    self.line("__html.push_str(\" class=\\\"\");");
    self.line("__html.push_str(&__classes.join(\" \"));");
    self.line("__html.push_str(\"\\\"\");");
    self.dedent();
    self.line("}");
    self.dedent();
    self.line("}");
  }

  /// Emit inline style properties as a single `style` attribute.
  ///
  /// For `style:color="text_color"` and `style:font-size="size"`, generates:
  /// ```text
  /// __html.push_str(" style=\"");
  /// __html.push_str("color: ");
  /// __html.push_str(&__esc(&format!("{}", { text_color })));
  /// __html.push_str("; font-size: ");
  /// __html.push_str(&__esc(&format!("{}", { size })));
  /// __html.push_str("\"");
  /// ```
  fn emit_style_props(&mut self, props: &[IrStyleProp]) {
    // Filter out props with empty values — they would produce invalid Rust.
    let valid: Vec<_> = props.iter().filter(|p| !p.value.trim().is_empty()).collect();
    if valid.is_empty() {
      return;
    }
    self.line("__html.push_str(\" style=\\\"\");");
    for (i, prop) in valid.iter().enumerate() {
      if i > 0 {
        self.line("__html.push_str(\"; \");");
      }
      self.line(&format!(
        "__html.push_str(\"{}: \");",
        esc_rs(&prop.property)
      ));
      self.line(&format!(
        "__html.push_str(&__esc(&format!(\"{{}}\", {{ {} }})));",
        prop.value
      ));
    }
    self.line("__html.push_str(\"\\\"\");");
  }

  /// Emit an event handler as a `data-on-EVENT` attribute for client hydration.
  ///
  /// Event modifiers are encoded as a pipe-separated list in a companion
  /// `data-on-EVENT-mod` attribute so the client runtime can apply them.
  fn emit_event_handler(&mut self, event: &IrEventHandler) {
    self.line(&format!(
      "__html.push_str(\" data-on-{}=\\\"{}\\\"\");",
      esc_rs(&esc_html_attr(&event.event)),
      esc_rs(&esc_html_attr(&event.handler)),
    ));
    if !event.modifiers.is_empty() {
      let mods: Vec<&str> = event.modifiers.iter().copied().map(modifier_name).collect();
      self.line(&format!(
        "__html.push_str(\" data-on-{}-mod=\\\"{}\\\"\");",
        esc_rs(&esc_html_attr(&event.event)),
        esc_rs(&esc_html_attr(&mods.join("|"))),
      ));
    }
  }

  /// Emit a two-way binding as a `data-bind-PROP` attribute for client hydration.
  fn emit_binding(&mut self, binding: &IrBinding) {
    self.line(&format!(
      "__html.push_str(\" data-bind-{}=\\\"{}\\\"\");",
      esc_rs(&esc_html_attr(&binding.property)),
      esc_rs(&esc_html_attr(&binding.expression)),
    ));
  }

  /// Emit an action hook as a `data-use-NAME` attribute for client hydration.
  fn emit_action(&mut self, action: &IrAction) {
    if action.argument.is_empty() {
      self.line(&format!(
        "__html.push_str(\" data-use-{}\");",
        esc_rs(&esc_html_attr(&action.name)),
      ));
    } else {
      self.line(&format!(
        "__html.push_str(\" data-use-{}=\\\"{}\\\"\");",
        esc_rs(&esc_html_attr(&action.name)),
        esc_rs(&esc_html_attr(&action.argument)),
      ));
    }
  }

  fn emit_if(&mut self, ib: &IrIf) {
    for (i, branch) in ib.branches.iter().enumerate() {
      if i == 0 {
        let cond = branch.condition.as_deref().unwrap_or("true");
        self.line(&format!("if {cond} {{"));
      } else if let Some(cond) = &branch.condition {
        self.line(&format!("}} else if {cond} {{"));
      } else {
        self.line("} else {");
      }
      self.indent();
      for child in &branch.children {
        self.emit_node(child);
      }
      self.dedent();
    }
    self.line("}");
  }

  fn emit_each(&mut self, each: &IrEach) {
    if let Some(idx) = &each.index {
      self.line(&format!(
        "for ({idx}, {}) in ({}).into_iter().enumerate() {{",
        each.binding, each.iterable
      ));
    } else {
      self.line(&format!(
        "for {} in {} {{",
        each.binding, each.iterable
      ));
    }
    self.indent();
    for child in &each.children {
      self.emit_node(child);
    }
    self.dedent();
    self.line("}");
  }

  fn emit_component(&mut self, comp: &IrComponentRef) {
    // SSR: call the component's render function and append its output.
    // Props are passed as keyword-style arguments. The component's render
    // function signature is expected to accept them in declaration order.
    if comp.props.is_empty() && comp.children.is_empty() {
      self.line(&format!(
        "__html.push_str(&{}::render());",
        comp.name
      ));
    } else if comp.children.is_empty() {
      // Pass props as arguments.
      let args = Self::build_prop_args(&comp.props);
      self.line(&format!(
        "__html.push_str(&{}::render({args}));",
        comp.name
      ));
    } else {
      // Component with children (default slot content).
      // Render children into __comp_slot by temporarily redirecting __html.
      self.line("{");
      self.indent();
      self.line("let mut __comp_slot = String::new();");
      self.line("std::mem::swap(&mut __html, &mut __comp_slot);");
      for child in &comp.children {
        self.emit_node(child);
      }
      self.line("std::mem::swap(&mut __html, &mut __comp_slot);");

      if comp.props.is_empty() {
        self.line(&format!(
          "__html.push_str(&{}::render_with_slot(&__comp_slot));",
          comp.name
        ));
      } else {
        let args = Self::build_prop_args(&comp.props);
        self.line(&format!(
          "__html.push_str(&{}::render_with_slot(&__comp_slot, {args}));",
          comp.name
        ));
      }
      self.dedent();
      self.line("}");
    }
  }

  /// Build a comma-separated argument string from component props.
  ///
  /// Each prop value is evaluated and converted to a string reference.
  /// Static values are passed directly; dynamic expressions are formatted.
  fn build_prop_args(props: &[IrAttribute]) -> String {
    props
      .iter()
      .map(|p| {
        if p.value.is_empty() {
          // Boolean prop — pass `true`.
          "true".to_string()
        } else {
          let all_static = p.value.iter().all(|v| matches!(v, TemplateNode::Text(_)));
          if all_static {
            let val: String = p
              .value
              .iter()
              .map(|v| match v {
                TemplateNode::Text(t) => t.as_str(),
                TemplateNode::Expr { .. } => unreachable!(),
              })
              .collect();
            format!("\"{}\"", esc_rs(&val))
          } else if p.value.len() == 1 {
            match &p.value[0] {
              TemplateNode::Expr { expr, .. } => format!("&format!(\"{{}}\", {{ {expr} }})"),
              TemplateNode::Text(t) => format!("\"{}\"", esc_rs(t)),
            }
          } else {
            // Mixed static/dynamic — build with format!.
            let mut fmt_str = String::new();
            let mut fmt_args = Vec::new();
            for part in &p.value {
              match part {
                TemplateNode::Text(t) => fmt_str.push_str(&esc_fmt(&esc_rs(t))),
                TemplateNode::Expr { expr, .. } => {
                  fmt_str.push_str("{}");
                  fmt_args.push(expr.clone());
                }
              }
            }
            if fmt_args.is_empty() {
              format!("\"{fmt_str}\"")
            } else {
              format!("&format!(\"{fmt_str}\", {})", fmt_args.join(", "))
            }
          }
        }
      })
      .collect::<Vec<_>>()
      .join(", ")
  }

  fn emit_slot(&mut self, slot: &IrSlot) {
    if let Some(name) = &slot.name {
      // Named slot: look up the slot variable `__slot_NAME`.
      let var = format!("__slot_{name}");
      self.line(&format!("if let Some(__named) = {var}.as_ref() {{"));
      self.indent();
      self.line("__html.push_str(__named);");
      self.dedent();
      if !slot.fallback.is_empty() {
        self.line("} else {");
        self.indent();
        for child in &slot.fallback {
          self.emit_node(child);
        }
        self.dedent();
      }
      self.line("}");
    } else if self.slotted {
      // Default slot in slotted mode: inject the passed slot content.
      self.line("__html.push_str(__slot);");
    } else {
      // Default slot in standalone mode: render fallback content.
      for child in &slot.fallback {
        self.emit_node(child);
      }
    }
  }

  // ── Style / escape helpers ──────────────────────────────────────────

  fn emit_style_constants(&mut self, c: &CompiledComponent) {
    self.line("/// CSS content of this component's style blocks.");
    if c.styles.is_empty() {
      self.line("pub const STYLES: &[&str] = &[];");
    } else {
      self.line("pub const STYLES: &[&str] = &[");
      self.indent();
      for style in &c.styles {
        if style.scoped {
          if let Some(id) = &style.scope_id {
            // Rewrite selectors to include the scope attribute.
            let rewritten = rewrite_scoped_css(&style.content, id);
            self.line(&format!("\"{}\",", esc_rs(&rewritten)));
          } else {
            self.line(&format!("\"{}\",", esc_rs(&style.content)));
          }
        } else {
          self.line(&format!("\"{}\",", esc_rs(&style.content)));
        }
      }
      self.dedent();
      self.line("];");
    }

    self.line("");

    let scope_ids: Vec<_> = c
      .styles
      .iter()
      .filter_map(|s| s.scope_id.as_ref())
      .collect();
    self.line("/// Scope identifiers for scoped style blocks.");
    if scope_ids.is_empty() {
      self.line("pub const SCOPE_IDS: &[&str] = &[];");
    } else {
      self.line("pub const SCOPE_IDS: &[&str] = &[");
      self.indent();
      for id in &scope_ids {
        self.line(&format!("\"{id}\","));
      }
      self.dedent();
      self.line("];");
    }
  }

  fn emit_esc(&mut self) {
    self.line("#[allow(dead_code)]");
    self.line("fn __esc(s: &str) -> String {");
    self.indent();
    self.line("let mut out = String::with_capacity(s.len());");
    self.line("for c in s.chars() {");
    self.indent();
    self.line("match c {");
    self.indent();
    self.line("'&' => out.push_str(\"&amp;\"),");
    self.line("'<' => out.push_str(\"&lt;\"),");
    self.line("'>' => out.push_str(\"&gt;\"),");
    self.line("'\"' => out.push_str(\"&quot;\"),");
    self.line("'\\'' => out.push_str(\"&#x27;\"),");
    self.line("_ => out.push(c),");
    self.dedent();
    self.line("}");
    self.dedent();
    self.line("}");
    self.line("out");
    self.dedent();
    self.line("}");
  }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/// Recursively collect all distinct named-slot names from a template tree.
///
/// Returns a sorted, deduplicated list of slot names so that the codegen
/// can emit `let __slot_NAME: Option<&str> = None;` declarations.
fn collect_named_slots(nodes: &[IrNode]) -> Vec<String> {
  let mut names = Vec::new();
  collect_named_slots_inner(nodes, &mut names);
  names.sort();
  names.dedup();
  names
}

fn collect_named_slots_inner(nodes: &[IrNode], out: &mut Vec<String>) {
  for node in nodes {
    match node {
      IrNode::Slot(slot) => {
        if let Some(name) = &slot.name {
          out.push(name.clone());
        }
        collect_named_slots_inner(&slot.fallback, out);
      }
      IrNode::Element(el) => {
        collect_named_slots_inner(&el.children, out);
      }
      IrNode::Component(comp) => {
        collect_named_slots_inner(&comp.children, out);
      }
      IrNode::If(ib) => {
        for branch in &ib.branches {
          collect_named_slots_inner(&branch.children, out);
        }
      }
      IrNode::Each(each) => {
        collect_named_slots_inner(&each.children, out);
      }
      IrNode::Text(_) | IrNode::Expr(_) => {}
    }
  }
}

/// Map an [`EventModifier`] variant to its canonical string name.
fn modifier_name(m: EventModifier) -> &'static str {
  match m {
    EventModifier::PreventDefault => "preventDefault",
    EventModifier::StopPropagation => "stopPropagation",
    EventModifier::Once => "once",
    EventModifier::Capture => "capture",
    EventModifier::Self_ => "self",
    EventModifier::Trusted => "trusted",
    EventModifier::Passive => "passive",
    EventModifier::NonPassive => "nonpassive",
  }
}

/// Escape a string for inclusion inside a Rust string literal.
fn esc_rs(s: &str) -> String {
  s.replace('\\', "\\\\")
    .replace('"', "\\\"")
    .replace('\n', "\\n")
    .replace('\r', "\\r")
    .replace('\t', "\\t")
}

/// Escape a string for safe inclusion in an HTML attribute value.
///
/// This prevents attribute injection and malformed HTML when user-supplied
/// strings (handler names, binding expressions, etc.) are embedded in
/// `data-*` attributes. Applied **before** [`esc_rs`] so the generated
/// Rust source emits valid, safe HTML at runtime.
fn esc_html_attr(s: &str) -> String {
  let mut out = String::with_capacity(s.len());
  for c in s.chars() {
    match c {
      '&' => out.push_str("&amp;"),
      '"' => out.push_str("&quot;"),
      '\'' => out.push_str("&#x27;"),
      '<' => out.push_str("&lt;"),
      '>' => out.push_str("&gt;"),
      _ => out.push(c),
    }
  }
  out
}

/// Escape literal `{` and `}` for use inside a `format!` string.
///
/// `{` → `{{`, `}` → `}}` so that they pass through `format!` as-is
/// instead of being interpreted as format placeholders.
fn esc_fmt(s: &str) -> String {
  s.replace('{', "{{").replace('}', "}}")
}

/// Rewrite CSS selectors to include a scoped attribute selector.
///
/// Parses the CSS with lightningcss, visits every selector, appends
/// `[data-SCOPE_ID]` to each compound selector, and serialises back.
/// At-rules like `@keyframes` and `@font-face` are automatically left
/// untouched because lightningcss's visitor only visits actual selectors.
fn rewrite_scoped_css(css: &str, scope_id: &str) -> String {
  use cssparser::ToCss as CssToCss;
  use lightningcss::stylesheet::{ParserOptions, PrinterOptions, StyleSheet};
  use lightningcss::traits::IntoOwned;
  use lightningcss::visitor::{Visit, VisitTypes, Visitor};

  let attr = format!("[data-{scope_id}]");

  let mut stylesheet = match StyleSheet::parse(css, ParserOptions::default()) {
    Ok(ss) => ss,
    Err(_) => return css.to_string(),
  };

  struct ScopeVisitor {
    attr: String,
  }

  impl<'i> Visitor<'i> for ScopeVisitor {
    type Error = std::convert::Infallible;

    fn visit_types(&self) -> VisitTypes {
      VisitTypes::SELECTORS
    }

    fn visit_selector(
      &mut self,
      selector: &mut lightningcss::selector::Selector<'i>,
    ) -> Result<(), Self::Error> {
      // 1. Serialize the selector to a CSS string.
      let sel_css = selector.to_css_string();

      // 2. Scope it using our text-based scoping.
      //    Handles comma-separated selectors (lightningcss already
      //    splits them, so we get one at a time here).
      let scoped = scope_selector(&sel_css, &self.attr);

      // 3. Parse the scoped selector back into AST.
      let mut input = cssparser::ParserInput::new(&scoped);
      let mut parser = cssparser::Parser::new(&mut input);
      if let Ok(new_sel) =
        <lightningcss::selector::Selector as lightningcss::traits::ParseWithOptions>::parse_with_options(
          &mut parser,
          &lightningcss::stylesheet::ParserOptions::default(),
        )
      {
        // 4. Convert to owned data so the lifetime is decoupled from
        //    the local `scoped` string, then assign.
        let owned: lightningcss::selector::Selector<'i> = new_sel.into_owned();
        *selector = owned;
      }
      Ok(())
    }
  }

  let mut visitor = ScopeVisitor { attr };
  let _ = stylesheet.visit(&mut visitor);

  stylesheet
    .to_css(PrinterOptions::default())
    .map(|r| r.code)
    .unwrap_or_else(|_| css.to_string())
}

/// Scope a single CSS selector by appending the scope attribute selector
/// to each simple selector in the compound/complex selector.
///
/// Handles:
/// - Pseudo-elements: `.btn::before` → `.btn[data-s-X]::before`
/// - Pseudo-classes: `.btn:hover` → `.btn[data-s-X]:hover`
/// - Combinators: `.a > .b` → `.a[data-s-X] > .b[data-s-X]`
fn scope_selector(selector: &str, attr: &str) -> String {
  if selector.is_empty() {
    return String::new();
  }

  // Split on combinators while preserving them.
  let parts = split_on_combinators(selector);
  let mut result = String::new();

  for part in &parts {
    let trimmed = part.trim();
    if trimmed.is_empty() {
      continue;
    }

    // Check if this part is a combinator.
    if matches!(trimmed, ">" | "+" | "~") {
      result.push(' ');
      result.push_str(trimmed);
      result.push(' ');
      continue;
    }

    // Descendant combinator (space between parts) — add space if needed.
    if !result.is_empty() && !result.ends_with(' ') {
      result.push(' ');
    }

    // Find where to insert the scope attribute: before pseudo-elements
    // and pseudo-classes.
    if let Some(pseudo_pos) = find_pseudo_boundary(trimmed) {
      result.push_str(&trimmed[..pseudo_pos]);
      result.push_str(attr);
      result.push_str(&trimmed[pseudo_pos..]);
    } else {
      result.push_str(trimmed);
      result.push_str(attr);
    }
  }

  result
}

/// Split a selector on CSS combinators (`>`, `+`, `~`, and whitespace).
///
/// Returns a list of parts where combinators are their own entries.
fn split_on_combinators(selector: &str) -> Vec<String> {
  let mut parts = Vec::new();
  let mut current = String::new();
  let mut chars = selector.chars().peekable();
  // Track bracket depth for attribute selectors like `[data-x]`.
  let mut bracket_depth: usize = 0;

  while let Some(&c) = chars.peek() {
    match c {
      '[' => {
        bracket_depth += 1;
        current.push(c);
        chars.next();
      }
      ']' => {
        bracket_depth = bracket_depth.saturating_sub(1);
        current.push(c);
        chars.next();
      }
      '>' | '+' | '~' if bracket_depth == 0 => {
        if !current.trim().is_empty() {
          parts.push(current.clone());
          current.clear();
        }
        parts.push(c.to_string());
        chars.next();
      }
      ' ' | '\t' | '\n' if bracket_depth == 0 => {
        // Could be a descendant combinator or just whitespace around
        // another combinator. Consume all whitespace.
        if !current.trim().is_empty() {
          parts.push(current.clone());
          current.clear();
        }
        while let Some(&ws) = chars.peek() {
          if ws == ' ' || ws == '\t' || ws == '\n' {
            chars.next();
          } else {
            break;
          }
        }
      }
      _ => {
        current.push(c);
        chars.next();
      }
    }
  }

  if !current.trim().is_empty() {
    parts.push(current);
  }

  parts
}

/// Find the byte position where pseudo-elements (`::`) or pseudo-classes
/// (`:`) begin in a simple selector, ignoring attribute selectors.
fn find_pseudo_boundary(selector: &str) -> Option<usize> {
  let mut i = 0;
  let bytes = selector.as_bytes();
  while i < bytes.len() {
    match bytes[i] {
      b'[' => {
        // Skip attribute selector.
        while i < bytes.len() && bytes[i] != b']' {
          i += 1;
        }
        if i < bytes.len() {
          i += 1; // skip ']'
        }
      }
      b':' => return Some(i),
      _ => i += 1,
    }
  }
  None
}
