pub mod diagnostics;
mod codegen;
mod error;
mod ir;
mod lower;
mod validate;
mod warning;

pub use codegen::generate;
pub use error::CompileError;
pub use ir::ClientScript;
pub use ir::CompiledComponent;
pub use ir::EventModifier;
pub use ir::IrAction;
pub use ir::IrAttribute;
pub use ir::IrBinding;
pub use ir::IrClassToggle;
pub use ir::IrComponentRef;
pub use ir::IrConst;
pub use ir::IrEach;
pub use ir::IrElement;
pub use ir::IrEventHandler;
pub use ir::IrExpr;
pub use ir::IrIf;
pub use ir::IrIfBranch;
pub use ir::IrNode;
pub use ir::IrSlot;
pub use ir::IrStyleProp;
pub use ir::ProcessedStyle;
pub use ir::SetupBlock;
pub use lower::lower;
pub use validate::validate;
pub use warning::ValidationWarning;
