[package]
name = "thebe-compiler"
description = "Compiler IR and lowering pass for .trs single-file components"
edition.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
thebe-ast = { path = "../thebe-ast" }
thiserror = "2.0.18"
ariadne = "0.6.0"
lightningcss = { version = "1.0.0-alpha.70", default-features = false, features = ["visitor", "into_owned"] }
cssparser = "0.33"
